# Getting Financial Data - Pandas Datareader

### Name: Shaima Alqahtani

### Introduction:

This time you will get data from a website.


### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

import yfinance as yf

import datetime as dt

### Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is).

In [3]:
start = dt.datetime(2015, 1, 1)
end = dt.datetime.today()

start

datetime.datetime(2015, 1, 1, 0, 0)

### Step 3. Get an API key for one of the APIs that are supported by Pandas Datareader, preferably for AlphaVantage.

If you do not have an API key for any of the supported APIs, it is easiest to get one for [AlphaVantage](https://www.alphavantage.co/support/#api-key). (Note that the API key is shown directly after the signup. You do *not* receive it via e-mail.)

(For a full list of the APIs that are supported by Pandas Datareader, [see here](https://pydata.github.io/pandas-datareader/readers/index.html). As the APIs are provided by third parties, this list may change.)

### Step 4. Use Pandas Datarader to read the daily time series for the Apple stock (ticker symbol AAPL) between 01/01/2015 and today, assign it to df_apple and print it.

In [5]:
df_apple = yf.download("AAPL", start=start, end=end)
df_apple["stock"] = "AAPL"
df_apple.head()

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open     Volume stock
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2015-01-02  24.214893  24.682226  23.776353  24.671151  212818400  AAPL
2015-01-05  23.532719  24.064282  23.346673  23.984547  257142000  AAPL
2015-01-06  23.534933  23.794069  23.173912  23.596948  263188400  AAPL
2015-01-07  23.864948  23.964616  23.632389  23.743131  160423600  AAPL
2015-01-08  24.781889  24.839475  24.075353  24.192741  237458000  AAPL

### Step 5. Add a new column "stock" to the dataframe and add the ticker symbol

In [6]:

df_apple["stock"] = "AAPL"
df_apple

Price            Close        High         Low        Open     Volume stock
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2015-01-02   24.214893   24.682226   23.776353   24.671151  212818400  AAPL
2015-01-05   23.532719   24.064282   23.346673   23.984547  257142000  AAPL
2015-01-06   23.534933   23.794069   23.173912   23.596948  263188400  AAPL
2015-01-07   23.864948   23.964616   23.632389   23.743131  160423600  AAPL
2015-01-08   24.781889   24.839475   24.075353   24.192741  237458000  AAPL
...                ...         ...         ...         ...        ...   ...
2026-04-13  259.200012  260.179993  256.660004  259.730011   36234700  AAPL
2026-04-14  258.829987  261.929993  257.190002  259.250000   48370700  AAPL
2026-04-15  266.429993  266.559998  257.809998  258.160004   49913500  AAPL
2026-04-16  263.399994  267.160004  261.269989  266.799988   43323100  AAPL
2026-04-17  270.230011  272.299988  266.720001  266.959991   61314800  AAPL

[2839 rows x 6 columns]

### Step 6. Repeat the two previous steps for a few other stocks, always creating a new dataframe: Tesla, IBM and Microsoft. (Ticker symbols TSLA, IBM and MSFT.)

In [7]:
df_tsla = yf.download("TSLA", start=start, end=end)
df_tsla["stock"] = "TSLA"

df_ibm = yf.download("IBM", start=start, end=end)
df_ibm["stock"] = "IBM"

df_msft = yf.download("MSFT", start=start, end=end)
df_msft["stock"] = "MSFT"

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

### Step 7. Combine the four separate dataFrames into one combined dataFrame df that holds the information for all four stocks

In [10]:

df = pd.concat([df_apple, df_tsla, df_ibm, df_msft])
df.head()

Price,Close,High,Low,Open,Volume,stock,Close,High,Low,Open,...,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,,TSLA,TSLA,TSLA,TSLA,...,IBM,IBM,IBM,IBM,IBM,MSFT,MSFT,MSFT,MSFT,MSFT
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-02,24.214893,24.682226,23.776353,24.671151,212818400.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-05,23.532719,24.064282,23.346673,23.984547,257142000.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-06,23.534933,23.794069,23.173912,23.596948,263188400.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-07,23.864948,23.964616,23.632389,23.743131,160423600.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-08,24.781889,24.839475,24.075353,24.192741,237458000.0,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 8. Shift the stock column into the index (making it a multi-level index consisting of the ticker symbol and the date).

In [11]:
df.set_index(keys="stock", append=True, inplace=True)
df

,Price,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume
,Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,TSLA,TSLA,TSLA,TSLA,TSLA,IBM,IBM,IBM,IBM,IBM,MSFT,MSFT,MSFT,MSFT,MSFT
Date,stock,,,,,,,,,,,,,,,,,,,,
2015-01-02,AAPL,24.214893,24.682226,23.776353,24.671151,212818400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-05,AAPL,23.532719,24.064282,23.346673,23.984547,257142000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-06,AAPL,23.534933,23.794069,23.173912,23.596948,263188400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-07,AAPL,23.864948,23.964616,23.632389,23.743131,160423600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-08,AAPL,24.781889,24.839475,24.075353,24.192741,237458000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-13,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,384.369995,384.540009,371.019989,373.609985,35745800.0
2026-04-14,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,393.109985,394.690002,386.519989,387.920013,37504500.0
2026-04-15,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,411.220001,414.369995,396.730011,398.000000,45063400.0
2026-04-16,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,420.260010,420.820007,412.140015,419.859985,41642400.0
2026-04-17,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,422.790009,431.579987,420.690002,424.820007,47812100.0

### Step 7. Create a dataFrame called vol, with the volume values.

In [13]:

vol = df[["Volume"]]
vol.head()

Price                  Volume
Ticker                   AAPL TSLA IBM MSFT
Date       stock
2015-01-02 AAPL   212818400.0  NaN NaN  NaN
2015-01-05 AAPL   257142000.0  NaN NaN  NaN
2015-01-06 AAPL   263188400.0  NaN NaN  NaN
2015-01-07 AAPL   160423600.0  NaN NaN  NaN
2015-01-08 AAPL   237458000.0  NaN NaN  NaN

### Step 8. Aggregate the data of volume to weekly.
Hint: Be careful to not sum data from the same week of 2015 and other years.

In [15]:
vol_weekly = (
    vol.reset_index()
    .set_index("Date")
    .groupby("stock")
    .resample("W")
    .sum()
)
vol_weekly.head()

C:\Users\Dell\AppData\Local\Temp\ipykernel_20476\750179661.py:6: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  .sum()

Price                   Volume                week   year
Ticker                    AAPL TSLA  IBM MSFT
stock Date
AAPL  2015-01-04  2.128184e+08  0.0  0.0  0.0    1   2015
      2015-01-11  1.133010e+09  0.0  0.0  0.0   10  10075
      2015-01-18  1.216906e+09  0.0  0.0  0.0   15  10075
      2015-01-25  7.949480e+08  0.0  0.0  0.0   16   8060
      2015-02-01  1.863371e+09  0.0  0.0  0.0   25  10075

### Step 9. Find all the volume traded in the year of 2015

In [17]:
vol_2015 = vol_weekly.loc[
    (slice(None), slice("2015-01-01", "2015-12-31")),
    :
]

vol_2015.head()

Price                   Volume                week   year
Ticker                    AAPL TSLA  IBM MSFT
stock Date
AAPL  2015-01-04  2.128184e+08  0.0  0.0  0.0    1   2015
      2015-01-11  1.133010e+09  0.0  0.0  0.0   10  10075
      2015-01-18  1.216906e+09  0.0  0.0  0.0   15  10075
      2015-01-25  7.949480e+08  0.0  0.0  0.0   16   8060
      2015-02-01  1.863371e+09  0.0  0.0  0.0   25  10075