# Pandas Essentials

**Pandas** provides fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both **easy and intuitive**. Pandas is also **very fast** since it builds on top of **NumPy**, which builds on top of **C**.

The community agreed alias for `pandas` is `pd`, so it has been standard practice:

In [16]:
import pandas as pd

### Bookmarks

**Task**: Bookmark the following references in your browswer. These are **Handy References** to use while working with Pandas, presented in three different ways:

- [Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)
- [Methods' Mind Map](https://xmind.ai/share/ugVH30g4)
- [Pandas Cookbook](https://pandas.pydata.org/docs/user_guide/cookbook.html)

## Read data in

Data can be loaded into a Pandas DataFrame from various sources and different formats:

1. **Databases**: relational (SQL) and unstructured (NoSQL)
2. **Surveys**: Google Forms, SurveyMonkey
3. **APIs**: Social Media Platforms, Open Street Maps, Flights, ..etc.
4. **Web Scraping**: BeautifulSoup, Scrapy, Selenium
5. **Raw Files**: csv, excel, txt, json, xml, pdf, ..etc.

Pandas provides the [`read_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv "pandas.read_csv") function to read data stored as a csv file into a pandas `DataFrame`. pandas supports many different file formats or data sources out of the box (csv, excel, sql, json, parquet, …), each of them with the prefix `read_*`.

![](../assets/pandas/pandas_io.png)

See: [IO tools (text, CSV, HDF5, …)](https://pandas.pydata.org/docs/user_guide/io.html) for a table containing available readers and writers.

In [17]:
help(pd.read_csv)

Help on function read_csv in module pandas:

read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols: 'UsecolsArgType' = None, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters: 'Mapping[HashableT, Callable] | None' = None, true_values: 'list | None' = None, false_values: 'list | None' = None, skipinitialspace: 'bool' = False, skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, skip_blank_lines: 'bool' = True, parse_dates: 'bool | Sequence[Hashable] | None' = None, date_format: 'str | dict[Hashable, str] | None' = None, dayfirst: 'bool' = False, cache_dates: 'bool' = True, iterator: 'bool' = False, chunksize: 'int | None' = None, compression: 'CompressionOptions' = 'infer', thousands: 'str | None' = None, decimal: 'str' = '.', lineterminator: 'str | None' = None, quotechar: 'str' = '"', quoting: 'int' = 0, doublequote: 'bool' = True, escapechar: 'str | None' = None, comment: 'str | None' = None, encoding: 'str | None' = None, encoding_errors: 'str | None' = 'strict', dialect: 'str | csv.Dialect | None' = None, on_bad_lines: 'str' = 'error', low_memory: 'bool' = True, memory_map: 'bool' = False, float_precision: "Literal['high', 'legacy', 'round_trip'] | None" = None, storage_options: 'StorageOptions | None' = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>) -> 'DataFrame | TextFileReader'
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Character or regex pattern to treat as the delimiter. If ``sep=None``, the
        C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator from only the first valid
        row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
        In addition, separators longer than 1 character and different from
        ``'\s+'`` will be interpreted as regular expressions and will also force
        the use of the Python parsing engine. Note that regex delimiters are prone
        to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, optional
        Alias for ``sep``.
    header : int, Sequence of int, 'infer' or None, default 'infer'
        Row number(s) containing column labels and marking the start of the
        data (zero-indexed). Default behavior is to infer the column names:
        if no ``names``
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly to ``names`` then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a :class:`~pandas.MultiIndex` on the columns
        e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.

        When inferred from the file contents, headers are kept distinct from
        each other by renaming duplicate names with a numeric suffix of the form
        ``".{{count}}"`` starting from 1, e.g. ``"foo"`` and ``"foo.1"``.
        Empty headers are named ``"Unnamed: {{i}}"`` or ``
        "Unnamed: {{i}}_level_{{level}}"``
        in the case of MultiIndex columns.
    names : Sequence of Hashable, optional
        Sequence of column labels to apply. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : Hashable, Sequence of Hashable or False, optional
        Column(s) to use as row label(s), denoted either by column labels or column
        indices.  If a sequence of labels or indices is given,
        :class:`~pandas.MultiIndex`
        will be formed for the row labels.

        Note: ``index_col=False`` can be used to force pandas to *not* use the first
        column as the index, e.g., when you have a malformed file with delimiters at
        the end of each line.
    usecols : Sequence of Hashable or Callable, optional
        Subset of columns to select, denoted either
        by column labels or column indices.
        If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in ``names`` or
        inferred from the document header row(s).
        If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
        preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
        for columns in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to ``True``. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    dtype : dtype or dict of {{Hashable : dtype}}, optional
        Data type(s) to apply to either the whole dataset or individual columns.
        E.g., ``{{'a': np.float64, 'b': np.int32, 'c': 'Int64'}}``
        Use ``str`` or ``object`` together with suitable ``na_values`` settings
        to preserve and not interpret ``dtype``.
        If ``converters`` are specified, they will be applied INSTEAD
        of ``dtype`` conversion. Specify a ``defaultdict`` as input where
        the default determines the ``dtype``
        of the columns which are not explicitly
        listed.
    engine : {{'c', 'python', 'pyarrow'}}, optional
        Parser engine to use. The C and pyarrow engines are faster,
        while the python engine
        is currently more feature-complete. Multithreading
        is currently only supported by
        the pyarrow engine. Some features of the "pyarrow" engine
        are unsupported or may not work correctly.
    converters : dict of {{Hashable : Callable}}, optional
        Functions for converting values in specified columns. Keys can either
        be column labels or column indices.
    true_values : list, optional
        Values to consider as ``True`` in addition
        to case-insensitive variants of 'True'.
    false_values : list, optional
        Values to consider as ``False`` in addition to case-insensitive
        variants of 'False'.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : int, list of int or Callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (``int``)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning ``True`` if the row should be skipped and ``False``
        otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
        Refers to the number of data rows in the returned DataFrame, excluding:

        * The header row containing column names.
        * Rows before the header row, if ``header=1`` or larger.

        Example usage:

        * To read the first 999,999 (non-header) rows:
          ``read_csv(..., nrows=999999)``

        * To read rows 1,000,000 through 1,999,999:
          ``read_csv(..., skiprows=1000000, nrows=999999)``

    na_values : Hashable, Iterable of Hashable or dict of {{Hashable : Iterable}},
        optional
        Additional strings to recognize as ``NA``/``NaN``. If ``dict``
        passed, specific
        per-column ``NA`` values.  By default the following values
        are interpreted as
        ``NaN``: empty string, "NaN", "N/A", "NULL", and other common
        representations of missing data.
    keep_default_na : bool, default True
        Whether or not to include the default ``NaN`` values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is ``True``, and ``na_values``
          are specified, ``na_values``
          is appended to the default ``NaN`` values used for parsing.
        * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
          the default ``NaN`` values are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
          the ``NaN`` values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
          strings will be parsed as ``NaN``.

        Note that if ``na_filter`` is passed in as ``False``,
        the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of ``na_values``). In
        data without any ``NA`` values, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    skip_blank_lines : bool, default True
        If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
    parse_dates : bool, None, list of Hashable, default None
        The behavior is as follows:

        * ``bool``. If ``True`` -> try parsing the index.
        * ``None``. Behaves like ``True`` if ``date_format`` is specified.
        * ``list`` of ``int`` or names.
          e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
          each as a separate date column.

        If a column or index cannot be represented as an array of ``datetime``,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an ``object`` data type. For
        non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
        :func:`~pandas.read_csv`.

        Note: A fast-path exists for iso8601-formatted dates.
    date_format : str or dict of column -> format, optional
        Format to use for parsing dates and/or times when
        used in conjunction with ``parse_dates``.
        The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
        `strftime documentation
        <https://docs.python.org/3/library/datetime.html
        #strftime-and-strptime-behavior>`_ for more information on choices, though
        note that :const:`"%f"`` will parse all the way up to nanoseconds.
        You can also pass:

        - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
          time string (not necessarily in exactly the same format);
        - "mixed", to infer the format for each element individually. This is risky,
          and you should probably use it along with `dayfirst`.

        .. versionadded:: 2.0.0
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If ``True``, use a cache of unique, converted dates to apply the ``datetime``
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

    iterator : bool, default False
        Return ``TextFileReader`` object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, optional
        Number of lines to read from the file per chunk. Passing a value will cause the
        function to return a ``TextFileReader`` object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data.
        If 'infer' and 'filepath_or_buffer' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        If using 'zip' or 'tar', the ZIP file must contain only
        one data file to be read in.
        Set to ``None`` for no decompression.
        Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``,
        ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for
        Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

    thousands : str (length 1), optional
        Character acting as the thousands separator in numerical values.
    decimal : str (length 1), default '.'
        Character to recognize as decimal point (e.g., use ',' for European data).
    lineterminator : str (length 1), optional
        Character used to denote a line break. Only valid with C parser.
    quotechar : str (length 1), optional
        Character used to denote the start and end of a quoted item. Quoted
        items can include the ``delimiter`` and it will be ignored.
    quoting : {{0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL,
        2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}}, default csv.QUOTE_MINIMAL
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
        ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that
        only fields containing special
        characters are quoted (e.g., characters defined
        in ``quotechar``, ``delimiter``,
        or ``lineterminator``.
    doublequote : bool, default True
        When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
        whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
        field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        Character used to escape other characters.
    comment : str (length 1), optional
        Character indicating that the remainder of line should not be parsed.
        If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter ``header`` but not by
        ``skiprows``. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
        treated as the header.
    encoding : str, optional, default 'utf-8'
        Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    encoding_errors : str, optional, default 'strict'
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
        ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
        override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
        documentation for more details.
    on_bad_lines : {{'error', 'warn', 'skip'}} or Callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are:

        - ``'error'``, raise an Exception when a bad line is encountered.
        - ``'warn'``, raise a warning when a bad line is
          encountered and skip that line.
        - ``'skip'``, skip bad lines without raising or warning when
          they are encountered.
        - Callable, function that will process a single bad line.
            - With ``engine='python'``, function with signature
              ``(bad_line: list[str]) -> list[str] | None``.
              ``bad_line`` is a list of strings split by the ``sep``.
              If the function returns ``None``, the bad line will be ignored.
              If the function returns a new ``list`` of strings with
              more elements than
              expected, a ``ParserWarning`` will be emitted while
              dropping extra elements.
            - With ``engine='pyarrow'``, function with signature
              as described in pyarrow documentation: `invalid_row_handler
              <https://arrow.apache.org/docs/python
              /generated/pyarrow.csv.ParseOptions.html
              #pyarrow.csv.ParseOptions.invalid_row_handler>`_.

        .. versionchanged:: 2.2.0

            Callable for ``engine='pyarrow'``

    low_memory : bool, default True
        Internally process the file in chunks, resulting in lower memory use
        while parsing, but possibly mixed type inference.  To ensure no mixed
        types either set ``False``, or specify the type with the ``dtype`` parameter.
        Note that the entire file is read into a single :class:`~pandas.DataFrame`
        regardless, use the ``chunksize`` or ``iterator``
        parameter to return the data in
        chunks. (Only valid with C parser).
    memory_map : bool, default False
        If a filepath is provided for ``filepath_or_buffer``, map the file object
        directly onto memory and access the data directly from there. Using this
        option can improve performance because there is no longer any I/O overhead.
    float_precision : {{'high', 'legacy', 'round_trip'}}, optional

The result of a `read_*` operation is a `DataFrame` (usually abbreviated as `df`), which is essentially a **table of rows and columns**.

![Figure: Pandas' DataFrame](../assets/pandas/dataframe.png)

Let's demonstrate:

### read from file on disk

In [18]:
# Best practice: use pathlib to handle file paths
from pathlib import Path

# Set the path to the directory containing the datasets
data_dir = Path('../../data')

# Debugging
print(data_dir.resolve())
print(data_dir.exists())

/home/halgoz/work/AthkaX/ai-pros/public/content/W2/data
True

In [19]:
data_wpm = data_dir / 'wpm.csv'

# Debugging
print(data_wpm.exists())
print(data_wpm.resolve())

True
/home/halgoz/work/AthkaX/ai-pros/public/content/W2/data/wpm.csv

Once we have specified the path, we load the data into a Python object; i.e., a `DataFrame`:

In [20]:
# Notice we use `df` to denote a DataFrame
df_1 = pd.read_csv(data_wpm)

# Debugging
df_1.head() # show first 5 rows

   wpm  light
0   11  False
1   15  False
2   50  False
3   13  False
4   15  False

### read from url

Alternatively, one could load the data from a url directly:

In [21]:
# GitHub URL (replace "blob" with "raw" to get the raw content)
data_url_wpm = "https://github.com/HassanAlgoz/B5/blob/main/content/W2/data/wpm.csv"
data_url_wpm = data_url_wpm.replace("blob", "raw")
df_2 = pd.read_csv(data_url_wpm)

# Debugging
df_2.tail() # show last 5 rows

    wpm  light
21   21   True
22   37   True
23   42   True
24   36   True
25   40   True

## DataFrame Metadata

The `head`/`tail`/`info` methods and the `dtypes` attribute are convenient for a first check:

In [22]:
# show only data types
df_2.dtypes

wpm      int64
light     bool
dtype: object

In [23]:
# show full technical details of the DataFrame
df_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   wpm     26 non-null     int64
 1   light   26 non-null     bool
dtypes: bool(1), int64(1)
memory usage: 366.0 bytes

## Creating a DataFrame

Sometimes, like in demonstration, you need to create a `DataFrame` object, not loaded from outside.

DataFrames can be constructed from Python dictionaries, like so:

In [24]:
df = pd.DataFrame(
    {
        'A': [10, 20, 30],
        'B': [40, 50, 60]
    }
)

df

    A   B
0  10  40
1  20  50
2  30  60

- Keys `'A'` and `'B'` become column labels
- Values become cell values

## Selecting a Subset of a DataFrame

More than a table though, a `DataFrame` also has:

- **Index**: to access rows (by position)
- **Label**: to access columns (by name)

In [25]:
# Show index
df_2.index

RangeIndex(start=0, stop=26, step=1)

In [26]:
# Show labels
df_2.columns

Index(['wpm', 'light'], dtype='str')

Once you access either a row or a column, you get back a `Series` object:

![](../assets/pandas/series.png)

### Select specific columns

![](../assets/pandas/subset_columns.png)

In [27]:
s_wpm = df_2['wpm']

# Debugging
# show last 8 rows
s_wpm.tail(8)

18    46
19    25
20    41
21    21
22    37
23    42
24    36
25    40
Name: wpm, dtype: int64

Notice the index on the left, from `18` to `25`, indicating the location of each row, in order.

Let's load a another csv and select subsets:

In [28]:
df_titanic = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")

In [29]:
# Show labels
df_titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [30]:
# Select specific columns
df_subset = df_titanic[['Name', 'Age', 'Sex']]
df_subset.head()

                                                Name   Age     Sex
0                            Braund, Mr. Owen Harris  22.0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                              Heikkinen, Miss Laina  26.0  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                           Allen, Mr. William Henry  35.0    male

### Select specific rows

![](../assets/pandas/subset_rows.png)

To select rows based on a conditional expression, use a condition inside the selection brackets `[]`, like so:

In [31]:
above_35 = df_titanic[df_titanic["Age"] > 35]

In [32]:
above_35.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S

Notice the index shows: `1`, `6`, `11`, `13` and `15`, which are the location of these rows in the original `DataFrame`.

#### Mask

The condition inside the selection brackets `titanic["Age"] > 35` checks for which rows the `Age` column has a value larger than 35. It is also known as a **boolean mask**, since it results in a `Series` of `True`/`False` values:

In [33]:
df_titanic["Age"] > 35

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

Only rows for which the value is `True` will be selected.

### combine row selection conditions

When combining multiple conditional statements, be careful:

1. each condition must be surrounded by parentheses `()`
2. you can not use `or`/`and` but need to use the or **operator `|`** and the **and operator `&`**.

In [34]:
# Condition 1
mask_1 = df_titanic["Age"] > 35

# Condition 2
mask_2 = df_titanic["Pclass"].isin([2, 3])

# Combine conditions
mask = mask_1 & mask_2

# Apply the mask to the DataFrame
above_35_df = df_titanic[mask]
above_35_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S

### select specific rows AND columns

![](../assets/pandas/subset_rows_and_columns.png)

Let's say, we're interested in the names of the passengers older than 65 years.

When selecting both rows AND columns, We can't just use the brackets `[]` notation directly, rather, we need to preceed add a `loc` or `iloc` method:

1. Use `loc` for label-based selection (using row/column names)
2. Use `iloc` for position-based selection (using table positions)

#### `loc`: label-based selection

In [35]:
seniors_names = df_titanic.loc[df_titanic["Age"] > 65, "Name"]
seniors_names.head()

33                    Wheadon, Mr. Edward H
96                Goldschmidt, Mr. George B
116                    Connors, Mr. Patrick
493                 Artagaveytia, Mr. Ramon
630    Barkworth, Mr. Algernon Henry Wilson
Name: Name, dtype: str

When using either `loc` or `iloc`:

1. the part before the comma is the **rows** you want
2. the part after the comma is the **columns** you want to select

Let's demonstrate combining conditions and multiple column selection:

In [36]:
condition = (df_titanic["Age"] > 65) & (df_titanic['Sex'] == 'male')
columns = ["Name", 'Pclass']

seniors = df_titanic.loc[condition, columns]
seniors.head()

                                     Name  Pclass
33                  Wheadon, Mr. Edward H       2
96              Goldschmidt, Mr. George B       1
116                  Connors, Mr. Patrick       3
493               Artagaveytia, Mr. Ramon       1
630  Barkworth, Mr. Algernon Henry Wilson       1

To demonstrate using the result, let's say we want to know the first names these people have:

In [ ]:
# convert Series to a Python list
names = seniors['Name'].to_list()

# show only first names
first_names = [x.split(',')[1].strip() for x in names]
first_names

['Mr. Edward H',
 'Mr. George B',
 'Mr. Patrick',
 'Mr. Ramon',
 'Mr. Algernon Henry Wilson',
 'Mr. Henry Michael',
 'Capt. Edward Gifford',
 'Mr. Johan']

#### `iloc`: position-based selection

In [62]:
df_titanic.iloc[2:5, 0:3]

   PassengerId  Survived  Pclass
2            3         1       3
3            4         1       1
4            5         0       3

- Row-wise, we are selecting from `2` to `5`
- Column-wise, we are selecting from `0` to `3`

## Summary: Indexing / selection

The basics of indexing are as follows:

| Operation                      | Syntax          | Result    |
| ------------------------------ | --------------- | --------- |
| Select column                  | `df[col]`       | Series    |
| Select row by label            | `df.loc[label]` | Series    |
| Select row by integer location | `df.iloc[loc]`  | Series    |
| Slice rows                     | `df[5:10]`      | DataFrame |
| Select rows by boolean vector  | `df[bool_vec]`  | DataFrame |

Source: https://pandas.pydata.org/docs/user_guide/dsintro.html#indexing-selection

## Create new columns derived from existing columns

![](../assets/pandas/create_new_columns.png)

Let's demonstrate calculate the BMI given weight and height of each athlete:

In [63]:
# Best practice: use pathlib to handle file paths
from pathlib import Path

# Set the path to the directory containing the datasets
data_dir = Path('../../data')

# Debugging
print(data_dir.resolve())
print(data_dir.exists())

/home/halgoz/work/AthkaX/ai-pros/public/content/W2/data
True

In [64]:
data_socr = data_dir / 'SOCR-HeightWeight.csv'

# Debugging
print(data_socr.exists())
print(data_socr.resolve())

True
/home/halgoz/work/AthkaX/ai-pros/public/content/W2/data/SOCR-HeightWeight.csv

**BMI formula**:

$$
BMI = \frac{\text{Weight}}{\text{Height}^2}
$$

In [65]:
df_socr = pd.read_csv(data_socr)
df_socr.head()

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

### Vector-scalar operations

Since the Height and Weight are in pounds, and the formula assumes **Metric System**, we need to convert the **Imperial System** numbers first:

In [66]:
df_socr['Height(meters)'] = df_socr['Height(Inches)'] * 0.0254
df_socr['Weight(kilograms)'] = df_socr['Weight(Pounds)'] * 0.453592
df_socr.head()

   Index  Height(Inches)  Weight(Pounds)  Height(meters)  Weight(kilograms)
0      1        65.78331        112.9925        1.670896          51.252494
1      2        71.51521        136.4873        1.816486          61.909547
2      3        69.39874        153.0269        1.762728          69.411778
3      4        68.21660        142.3354        1.732702          64.562199
4      5        67.78781        144.2971        1.721810          65.452010

Notice how we are multiplying a **scalar** like `0.0254` by a **vector** (`Series`). This is done **element-wise** (on each element), known as **Broadcasting** the operation.

### Row-wise calculations

Then actually do the calculation:

In [67]:
df_socr['BMI'] = df_socr['Weight(kilograms)'] / (df_socr['Height(meters)'] ** 2)
df_socr.head()

,Index,Height(Inches),Weight(Pounds),Height(meters),Weight(kilograms),BMI
0,1,65.78331,112.9925,1.670896,51.252494,18.357609
1,2,71.51521,136.4873,1.816486,61.909547,18.762615
2,3,69.39874,153.0269,1.762728,69.411778,22.338940
3,4,68.21660,142.3354,1.732702,64.562199,21.504569
4,5,67.78781,144.2971,1.721810,65.452010,22.077625

Notice how this involves calculation **across two columns of the corresponding row**.

### `apply` functions to calculate values

**BMI table for adults**. This is the World Health Organization's (WHO) recommended body weight based on BMI values for adults. It is used for both men and women, age 20 or older:

| Classification    | BMI range - kg/m2 |
| ----------------- | ----------------- |
| Severe Thinness   | < 16              |
| Moderate Thinness | 16 - 17           |
| Mild Thinness     | 17 - 18.5         |
| Normal            | 18.5 - 25         |
| Overweight        | 25 - 30           |
| Obese Class I     | 30 - 35           |
| Obese Class II    | 35 - 40           |
| Obese Class III   | > 40              |

Source: https://www.calculator.net/bmi-calculator.html

We can code this mapping as a pure Python function:

In [68]:
def get_bmi_category(bmi: float) -> str:
    if bmi < 16:
        return 'Severe Thinness'
    elif bmi < 17:
        return 'Moderate Thinness'
    elif bmi < 18.5:
        return 'Mild Thinness'
    elif bmi < 25:
        return 'Normal'
    elif bmi < 30:
        return 'Overweight'
    elif bmi < 35:
        return 'Obese Class I'
    elif bmi < 40:
        return 'Obese Class II'
    else:
        return 'Obese Class III'

Then use `apply` to process each value in the column, as follows:

In [69]:
df_socr['classification'] = df_socr['BMI'].apply(get_bmi_category)

Let's sample (randomly) 10 rows to see their classifications:

In [70]:
df_socr.sample(10)

,Index,Height(Inches),Weight(Pounds),Height(meters),Weight(kilograms),BMI,classification
16224,16225,68.00087,134.7445,1.727222,61.119027,20.487080,Normal
20115,20116,67.95350,149.5604,1.726019,67.839401,22.771462,Normal
24983,24984,63.77967,111.4911,1.620004,50.571471,19.269641,Normal
19789,19790,68.91363,119.3353,1.750406,54.129537,17.666749,Mild Thinness
2965,2966,66.24642,113.4835,1.682659,51.475208,18.180501,Mild Thinness
19687,19688,70.13351,140.4419,1.781391,63.703322,20.074443,Normal
9867,9868,70.77882,123.2178,1.797782,55.890608,17.292778,Mild Thinness
7218,7219,66.53305,135.1808,1.689939,61.316929,21.470299,Normal
17234,17235,68.30939,138.8029,1.735059,62.959885,20.913931,Normal
19884,19885,70.21997,121.1117,1.783587,54.935298,17.268824,Mild Thinness

Based on that, one could do lots of things like, `value_counts`:

In [71]:
df_socr['classification'].value_counts()

classification
Normal               17551
Mild Thinness         5780
Moderate Thinness     1262
Severe Thinness        401
Overweight               6
Name: count, dtype: int64

### Dropping columns

We might choose to drop the previous columns as well:

In [ ]:
df_socr = df_socr.drop(
    columns=['Height(Inches)', 'Weight(Pounds)'],
)
df_socr.head()

   Index  Height(meters)  Weight(kilograms)        BMI classification
0      1        1.670896          51.252494  18.357609  Mild Thinness
1      2        1.816486          61.909547  18.762615         Normal
2      3        1.762728          69.411778  22.338940         Normal
3      4        1.732702          64.562199  21.504569         Normal
4      5        1.721810          65.452010  22.077625         Normal

### Rename columns

Let's say we want to rename from `meters` to `m`, and from `kilograms` to `kg` instead:

In [73]:
df_socr = df_socr.rename(
    columns={
        'Height(meters)': 'Height(m)',
        'Weight(kilograms)': 'Weight(kg)',
    }
)
df_socr.head()

   Index  Height(m)  Weight(kg)        BMI classification
0      1   1.670896   51.252494  18.357609  Mild Thinness
1      2   1.816486   61.909547  18.762615         Normal
2      3   1.762728   69.411778  22.338940         Normal
3      4   1.732702   64.562199  21.504569         Normal
4      5   1.721810   65.452010  22.077625         Normal

## Key Takeaways

- **DataFrames** are core to pandas: they provide labeled, 2-dimensional data structures, allowing flexible and powerful manipulation and analysis of tabular data.

- **Reading Data:** Easily load data from various sources (CSV, Excel, SQL, web, etc.) with functions like `pd.read_csv()`.

- **Quick Inspection:** Use methods such as `.head()`, `.tail()`, `.info()`, and `.dtypes` to quickly get an overview of your data.

- **Selecting Data:**
  - Select columns as `df["col"]` or `df[["col1", "col2"]]`.
  - Select rows using slicing or with boolean conditions, e.g., `df[df['Age'] > 35]`.
  - Use `.loc[]` for selection by labels and `.iloc[]` for selection by integer position.

- **Vectorized Operations:** Arithmetic and logical operations between columns or between columns and scalars are applied elementwise (“broadcasting”).

- **Modifying DataFrames:**
  - Add new columns by assignment (e.g. `df["BMI"] = ...`).
  - Apply functions on values of a column using `apply(func)`
  - Drop columns with `df.drop(columns=[...])`.
  - Rename columns with `df.rename(columns={...})`.

- **Chaining Conditions:** Combine multiple boolean conditions with `&` (and), `|` (or), using parentheses as needed.

These core tools and concepts are essential for effective data exploration, cleaning, and analysis using pandas.

---

References: 

- [What kind of data does pandas handle?](https://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html#)
- [How do I read and write tabular data?](https://pandas.pydata.org/docs/getting_started/intro_tutorials/02_read_write.html)
- [How do I select a subset of a DataFrame?](https://pandas.pydata.org/docs/getting_started/intro_tutorials/03_subset_data.html)
- [How to create new columns derived from existing columns](https://pandas.pydata.org/docs/getting_started/intro_tutorials/05_add_columns.html)