# Housing Market

## Name: Shaima Alqahtani

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [8]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [9]:
s1 = pd.Series(np.random.randint(1, high=5, size=100, dtype='l'))
s2 = pd.Series(np.random.randint(1, high=4, size=100, dtype='l'))
s3 = pd.Series(np.random.randint(10000, high=30001, size=100, dtype='l'))

print(s1, s2, s3)

0     3
1     3
2     1
3     3
4     4
     ..
95    4
96    2
97    3
98    4
99    3
Length: 100, dtype: int32 0     2
1     2
2     1
3     2
4     2
     ..
95    3
96    1
97    1
98    1
99    1
Length: 100, dtype: int32 0     15950
1     16705
2     23677
3     26510
4     27333
      ...
95    22622
96    16758
97    19775
98    25365
99    23834
Length: 100, dtype: int32

### Step 3. Let's create a DataFrame by joinning the Series by column

In [10]:
housemkt = pd.concat([s1, s2, s3], axis=1)
housemkt

    0  1      2
0   3  2  15950
1   3  2  16705
2   1  1  23677
3   3  2  26510
4   4  2  27333
.. .. ..    ...
95  4  3  22622
96  2  1  16758
97  3  1  19775
98  4  1  25365
99  3  1  23834

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [11]:
housemkt.rename(columns = {0: 'bedrs', 1: 'bathrs', 2: 'price_sqr_meter'}, inplace=True)
housemkt

    bedrs  bathrs  price_sqr_meter
0       3       2            15950
1       3       2            16705
2       1       1            23677
3       3       2            26510
4       4       2            27333
..    ...     ...              ...
95      4       3            22622
96      2       1            16758
97      3       1            19775
98      4       1            25365
99      3       1            23834

[100 rows x 3 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [12]:
bigcolumn = pd.concat([s1, s2, s3], axis=0)
bigcolumn = bigcolumn.to_frame()

print(type(bigcolumn))
bigcolumn

<class 'pandas.DataFrame'>

        0
0       3
1       3
2       1
3       3
4       4
..    ...
95  22622
96  16758
97  19775
98  25365
99  23834

[300 rows x 1 columns]

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [13]:
len(bigcolumn)

300

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [14]:
bigcolumn.reset_index(drop=True, inplace=True)
bigcolumn

         0
0        3
1        3
2        1
3        3
4        4
..     ...
295  22622
296  16758
297  19775
298  25365
299  23834

[300 rows x 1 columns]